


ui <- fluidPage(
  titlePanel("Mental Disorder Predictor"),
  sidebarLayout(
    sidebarPanel(
      textInput("name","Please enter your name"),
      sliderInput("age","Choose your age (Move the slider)",min=1,max=100,value=20,step=1),
      radioButtons("gender","Choose your gender (Click either one)",
                   choices = c("Male","Female")),
      radioButtons("checkPrevious","Did you experience any mental disorder before?",
                   choices = c("Yes","No")),
      selectInput("disorderType","Select a mental disoder",
                  choices = c("Mood Disorder","Anxiety Disorder",
                              "Eating Disorder",
                              "Trauma-Related Disorder")),
      conditionalPanel(condition="input.disorderType == 'Mood Disorder'",
                       radioButtons("AEnter1", "Question 1",
                                    choices = c("Yes","No")),
                       radioButtons("AEnter2", "Question 2",
                                    choices = c("Yes","No")),
                       radioButtons("AEnter3", "Question 3",
                                    choices = c("Yes","No")),
                       radioButtons("AEnter4", "Question 4",
                                    choices = c("Yes","No")),
                       radioButtons("AEnter5", "Question 5",
                                    choices = c("Yes","No")),
                       radioButtons("AEnter6", "Question 6",
                                    choices = c("Yes","No")),
                       radioButtons("AEnter7", "Question 7",
                                    choices = c("Yes","No")),
                       radioButtons("AEnter8", "Question 8",
                                    choices = c("Yes","No")),
                       radioButtons("AEnter9", "Question 9",
                                    choices = c("Yes","No")),
                       radioButtons("AEnter10", "Question 10",
                                    choices = c("Yes","No"))),
      conditionalPanel(condition="input.disorderType == 'Anxiety Disorder'",
                       radioButtons("BEnter1", "Question 1",
                                    choices = c("Yes","No")),
                       radioButtons("BEnter2", "Question 2",
                                    choices = c("Yes","No")),
                       radioButtons("BEnter3", "Question 3",
                                    choices = c("Yes","No")),
                       radioButtons("BEnter4", "Question 4",
                                    choices = c("Yes","No")),
                       radioButtons("BEnter5", "Question 5",
                                    choices = c("Yes","No")),
                       radioButtons("BEnter6", "Question 6",
                                    choices = c("Yes","No")),
                       radioButtons("BEnter7", "Question 7",
                                    choices = c("Yes","No")),
                       radioButtons("BEnter8", "Question 8",
                                    choices = c("Yes","No")),
                       radioButtons("BEnter9", "Question 9",
                                    choices = c("Yes","No")),
                       radioButtons("BEnter10", "Question 10",
                                    choices = c("Yes","No"))),
      conditionalPanel(condition="input.disorderType == 'Eating Disorder'",
                       radioButtons("CEnter1", "Question 1",
                                    choices = c("Yes","No")),
                       radioButtons("CEnter2", "Question 2",
                                    choices = c("Yes","No")),
                       radioButtons("CEnter3", "Question 3",
                                    choices = c("Yes","No")),
                       radioButtons("CEnter4", "Question 4",
                                    choices = c("Yes","No")),
                       radioButtons("CEnter5", "Question 5",
                                    choices = c("Yes","No")),
                       radioButtons("CEnter6", "Question 6",
                                    choices = c("Yes","No")),
                       radioButtons("CEnter7", "Question 7",
                                    choices = c("Yes","No")),
                       radioButtons("CEnter8", "Question 8",
                                    choices = c("Yes","No")),
                       radioButtons("CEnter9", "Question 9",
                                    choices = c("Yes","No")),
                       radioButtons("CEnter10", "Question 10",
                                    choices = c("Yes","No"))),
      conditionalPanel(condition="input.disorderType == 'Trauma-Related Disorder'",
                       radioButtons("DEnter1", "Question 1",
                                    choices = c("Yes","No")),
                       radioButtons("DEnter2", "Question 2",
                                    choices = c("Yes","No")),
                       radioButtons("DEnter3", "Question 3",
                                    choices = c("Yes","No")),
                       radioButtons("DEnter4", "Question 4",
                                    choices = c("Yes","No")),
                       radioButtons("DEnter5", "Question 5",
                                    choices = c("Yes","No")),
                       radioButtons("DEnter6", "Question 6",
                                    choices = c("Yes","No")),
                       radioButtons("DEnter7", "Question 7",
                                    choices = c("Yes","No")),
                       radioButtons("DEnter8", "Question 8",
                                    choices = c("Yes","No")),
                       radioButtons("DEnter9", "Question 9",
                                    choices = c("Yes","No")),
                       radioButtons("DEnter10", "Question 10",
                                    choices = c("Yes","No"))),
      hr(),#new line
      actionButton("predict","Predict",class = "btn btn-primary btn btn active")
    ),
    
    mainPanel(
      tabsetPanel(type = "tabs",
                  tabPanel("Details",
                           h3(paste("User Input Details")),
                           hr(),
                           h4(paste("Name:")),
                           verbatimTextOutput("name"),
                           h4(paste("Age:")),
                           verbatimTextOutput("age"),
                           h4(paste("Gender:")),
                           verbatimTextOutput("gender"),
                           h4(paste("Did you experience any mental disorder before:")),
                           verbatimTextOutput("check"),
                           h4(paste("Selected mental disorder:")),
                           verbatimTextOutput("selected"),
                           h4(textOutput("Q1")),
                           verbatimTextOutput("A1"),
                           h4(textOutput("Q2")),
                           verbatimTextOutput("A2"),
                           h4(textOutput("Q3")),
                           verbatimTextOutput("A3"),
                           h4(textOutput("Q4")),
                           verbatimTextOutput("A4"),
                           h4(textOutput("Q5")),
                           verbatimTextOutput("A5"),
                           h4(textOutput("Q6")),
                           verbatimTextOutput("A6"),
                           h4(textOutput("Q7")),
                           verbatimTextOutput("A7"),
                           h4(textOutput("Q8")),
                           verbatimTextOutput("A8"),
                           h4(textOutput("Q9")),
                           verbatimTextOutput("A9"),
                           h4(textOutput("Q10")),
                           verbatimTextOutput("A10")),
                  
                  
                  
                  
                  tabPanel("Result and Suggestion",
                           h2(paste("Type of Mental Disorders:")),
                           hr(),
                           h3(textOutput("type")),
                           h3(verbatimTextOutput("test"))),
                  tabPanel("Description"),
                  tabPanel("Dataset"),
                  tabPanel("About")),
      
    )
  )
)